/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Templates;

import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import Entities.Book;
import Entities.User;
import java.awt.Color;

/**
 *
 * @author raj
 */
public class BookTemplate extends javax.swing.JPanel implements ListCellRenderer<Book> {

    /**
     * Creates new form BookTemplate
     */
    public BookTemplate() {
        setOpaque(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        book_image_label = new javax.swing.JLabel();
        book_name_label = new javax.swing.JLabel();
        book_edition_label = new javax.swing.JLabel();
        book_price_label = new javax.swing.JLabel();
        book_hand_label = new javax.swing.JLabel();
        book_supplier_label = new javax.swing.JLabel();
        supplier_rating_bar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        book_image_label.setText("Book Images");

        book_name_label.setText("Book Name");

        book_edition_label.setText("Book Edition");

        book_price_label.setText("Book Price");

        book_hand_label.setText("Book Hand");

        book_supplier_label.setText("Book Supplier");

        jLabel1.setText("ADD TO CART");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(book_image_label, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(book_supplier_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addComponent(supplier_rating_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(book_name_label)
                                    .addComponent(book_edition_label)
                                    .addComponent(book_price_label)
                                    .addComponent(book_hand_label))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(book_image_label, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(supplier_rating_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(book_name_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(book_edition_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(book_price_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(book_hand_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(book_supplier_label)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel book_edition_label;
    private javax.swing.JLabel book_hand_label;
    private javax.swing.JLabel book_image_label;
    private javax.swing.JLabel book_name_label;
    private javax.swing.JLabel book_price_label;
    private javax.swing.JLabel book_supplier_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar supplier_rating_bar;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends Book> list, 
            Book book, int index, boolean isSelected, boolean cellHasFocus) {

        if(book == null){
            System.out.println("Book is NULL");
        }
        
        book_name_label.setText(book.getBookName());
        book_price_label.setText(Double.toString(book.getUnitPrice()));
        book_edition_label.setText(Integer.toString(book.getEdition()));
        book_hand_label.setText(Integer.toString(book.getHandNo()));
        User supplier = loadUser(book.getSupplierId());
        book_supplier_label.setText(book.getSupplierId());
        supplier_rating_bar.setValue(5);
        
        if(isSelected){
            setBackground(Color.BLUE);
            setForeground(Color.LIGHT_GRAY);
        }else{
            setBackground(list.getBackground());
            setForeground(list.getForeground());
        }
        return this;
    }

    private User loadUser(String supplierId) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    
        return null;
    }
}
